project_id          = "aqueous-thought-461705-k1"
project_name        = "my-first-project"
user_account        = "ankush.katkurwar30@gmail.com"
gcp_region_central  = "us-central1"
gcp_private_region  = "us-east1"
mysql_root_password = "root123456."
